'use strict';
(() => {
const $=id=>document.getElementById(id), V=THREE.Vector3, M=THREE.Matrix4, S=Spatial;
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});}catch{$('start').textContent='请在支持 WebGL 的 Edge / Chrome 中打开';return;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;$('world').appendChild(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.08,170);camera.rotation.order='YXZ';
const hemi=new THREE.HemisphereLight(0xe4f4e0,0x8d9181,2);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffe1ae,3);sun.position.set(-14,26,13);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-42,right:42,top:42,bottom:-42,near:.5,far:90});sun.shadow.bias=-.0007;scene.add(sun);
const colors={stone:0xe5dfc8,side:0xb2b3a0,cream:0xf0e5c7,dark:0x344e44,wood:0xa77951,leaf:0x718953,leaf2:0xa5ac6f,teal:0x6dafa1,rust:0xc18468,gold:0xdfb75f,white:0xf8f3e2,photoBlue:0x285aaf,photoWhite:0xd5e8f7,photoOchre:0xd1a563,photoUmber:0x765136};
const mats={};for(const [k,c] of Object.entries(colors))mats[k]=new THREE.MeshStandardMaterial({color:c,roughness:k==='gold'?.38:.86});
for(const key of ['stone','side','cream','rust','wood'])mats[key].onBeforeCompile=shader=>{shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 vGrainPosition;').replace('#include <begin_vertex>','#include <begin_vertex>\nvGrainPosition = (modelMatrix * vec4(position, 1.0)).xyz;');shader.fragmentShader=shader.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 vGrainPosition;').replace('#include <color_fragment>','#include <color_fragment>\nfloat grain = fract(sin(dot(floor(vGrainPosition * 140.0),vec3(12.9898,78.233,37.719))) * 43758.5453);\ndiffuseColor.rgb *= mix(0.94,1.02,grain);');};
const glow=new THREE.MeshBasicMaterial({color:0xf4d690}),ghostMat=new THREE.MeshStandardMaterial({color:0xa4d6b1,transparent:true,opacity:.24,depthWrite:false,roughness:.6});
let group,decor,preview=new THREE.Group(),records=[],photos=[],selected=0,history=[],develop=null,sourceSets={};let portal,battery,batteryPos,charged=false,carrying=false,pickups=[],copier,handBattery,socket,socketPos,batteryLabel;let cameraOwned=false,film=0,cameraPickup=null,batteryDock='ground',restored=false,memoryLamps=[];
const pos=new V(0,1.68,3.6),safe=new V(0,1.68,3.6),keys=new Set();let yaw=0,pitch=0,vy=0,grounded=true,level=0,mode='intro',holding=false,roll=0,distance=0,scale=1,drag=false,px=0,py=0,elapsed=0,total=0,noticeEnd=0,maxUnlocked=0;
const reduceMotion=typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches;
const levels=[
 {name:'风的庭院',goal:[0,0,-21],platforms:[[0,0,0,16,12],[0,0,-21,9,7]],sky:0xb2c9bd,starter:['bridge'],title:'让照片里的路，接上眼前的空白。',hint:'先到附近发光的相片架拾取照片。C 举起，在前方边缘对齐后 E 放置。',help:'站到前方金色圆环中央，面向出口。C 举起照片，保持默认角度、距离与大小，按 E。'},
 {name:'昨日的庭院',temporal:true,goal:[0,0,-21],platforms:[[0,0,0,18,12],[0,0,-21,16,7]],sky:0xc3c7be,starter:['bridge'],wall:true,title:'把昨日的长桥，带回坍塌的庭院。',hint:'先拾取左前方的旧照片。断桥左侧是 01 灯，右侧是 02 灯；让旧桥连接两处灯柱下的记忆点。',help:'拾取左侧旧照片，在前方圆环 C 举起、E 显影。旧桥会连接坍塌的缺口，接通两盏记忆灯后，出口开启。放错可按 Z 取回照片。'},
 {name:'侧着的天空',goal:[0,3,-21],platforms:[[0,0,0,16,12],[0,3,-21,9,7]],sky:0xc4c4d0,starter:['turned'],title:'把倾斜的记忆，转回现实。',hint:'先拾取前方工作台上的相机。再把阶梯照片旋转 90°，也可以用 F 拍摄自己的通路。',help:'前方站位线举起阶梯照片，按 R 一次转 90°，再 E 放置。它会恢复成向上的阶梯。'},
 {name:'停电的暗房',copierBattery:true,battery:[1,0,-1.5],goal:[0,0,-37],platforms:[[0,0,0,16,12],[0,0,-19,8,10],[0,0,-37,9,10]],sky:0xb0c4c7,starter:['bridge'],title:'同一块电池，照亮暗房与出口。',hint:'前方取电池 → E 插入右侧复印机 → E 复印 → G 取回电池。再搭两段桥，把电池送到出口电源座。',help:'本关没有胶卷。拾取长桥照片，去前方金色电池旁按 E；靠近右侧复印机 E 插入，再 E 复印。G 拔出电池后出发。两段桥各消耗一张照片，终点电源座按 E 插入。'},
 {name:'借来的光',goal:[21,3,0],platforms:[[0,0,0,16,12],[21,3,0,8,10]],sky:0xbac8a7,starter:['stairs'],east:true,battery:[18,3,1.2],title:'把一束光，带到它该去的地方。',hint:'出口在右侧高处。先搭阶梯，再取电池，带到电缆连接的电源座按 E 插入。',help:'走到右侧金色圆环，面向右侧出口。C 举起阶梯、E 放置。上去后 C 放下照片，靠近电池按 E。'},
 {name:'拼接天空',goal:[21,3,-19],platforms:[[0,0,0,16,12],[0,0,-19,10,10],[21,3,-19,8,10]],sky:0xcdb9a9,starter:['bridge','stairs'],battery:[0,0,-19],title:'两张照片，接通最后一封来信。',hint:'先拾取长桥照片过桥。中间露台上有第二张阶梯照片和电池，再向右登高。',help:'第一张桥连接中间露台；在那里靠近金色电池按 E。再站到露台右侧金色圆环，面向右侧出口，拾取阶梯照片后显影。'}
];

const themes=[
 {name:'碧海与白墙',sky:0x86cbe8,palette:{stone:0xf2e6c5,side:0x77adbf,cream:0xf9f0d7,rust:0xec9879,teal:0x28b8bd,leaf:0x3c9b66,leaf2:0x91c765,wood:0xb87845}},
 {name:'赭红日落',sky:0xf2b47c,palette:{stone:0xf2c58d,side:0xb97065,cream:0xffe1ac,rust:0xcc4f3f,teal:0x2c95ad,leaf:0x3d7479,leaf2:0x64a092,wood:0x774456}},
 {name:'紫色画廊',sky:0xb8adef,palette:{stone:0xeee6ff,side:0x9585c4,cream:0xfaf0ff,rust:0xdb83b2,teal:0x64cddd,leaf:0x9b69be,leaf2:0xeb9acb,wood:0x7a5c93}},
 {name:'深蓝星河',sky:0x203655,palette:{stone:0xaccadc,side:0x425477,cream:0xd5e5e9,rust:0xd38958,teal:0x49d1d0,leaf:0x276f81,leaf2:0x69a6b4,wood:0x7e6081}},
 {name:'翡翠温室',sky:0x83c4ae,palette:{stone:0xe5edb5,side:0x6aa897,cream:0xf5f0ca,rust:0xe892b6,teal:0x269e89,leaf:0x26885b,leaf2:0xa0d160,wood:0xb08147}},
 {name:'珊瑚天际',sky:0xf2b8a3,palette:{stone:0xffdfc9,side:0xb598c1,cream:0xffeecc,rust:0xe87076,teal:0x748bd4,leaf:0xc97897,leaf2:0xf1b878,wood:0x986586}}
];
function applyTheme(n){const t=themes[n];for(const [key,color] of Object.entries(colors))mats[key].color.set(t.palette[key]??color);scene.background=new THREE.Color(t.sky);scene.fog=new THREE.Fog(t.sky,40,130);document.documentElement.style.setProperty('--mint','#'+new THREE.Color(t.palette.teal).getHexString());}
function makeExtraSource(kind,x){const start=records.length;box(x,-.3,0,4.4,.6,4,'cream');if(kind==='archway'){box(x,-.3,-3.5,4.4,.6,7,'cream');box(x-1.5,1.4,-3,.5,2.8,.6,'rust');box(x+1.5,1.4,-3,.5,2.8,.6,'rust');box(x,2.9,-3,3.5,.3,.65,'gold');}else if(kind==='stepping'){for(let i=0;i<4;i++)box(x+(i%2?.5:-.5),.15+i*.2,-2-i*1.7,3, .5+i*.4,1.45,i%2?'teal':'rust');}else{const m=new M().makeTranslation(x,1.05,-3).multiply(new M().makeRotationX(.28));record(S.transform(S.box(0,0,0,4.4,.35,8),m),'teal');}sourceSets[kind]={x,records:records.slice(start)};}
function spawnPickup(photo,position,required){const g=new THREE.Group();g.position.copy(position);decor.add(g);const paper=new THREE.Mesh(new THREE.PlaneGeometry(.76,.64),new THREE.MeshBasicMaterial({color:0xfff5d5,side:THREE.DoubleSide}));paper.rotation.x=-.2;g.add(paper);const pictureMaterial=new THREE.MeshBasicMaterial({color:0xffffff,side:THREE.DoubleSide});const picture=new THREE.Mesh(new THREE.PlaneGeometry(.66,.47),pictureMaterial);picture.position.set(0,.035,.012);picture.rotation.x=-.2;g.add(picture);if(THREE.TextureLoader){new THREE.TextureLoader().load(photo.image,t=>{t.colorSpace=THREE.SRGBColorSpace;pictureMaterial.map=t;pictureMaterial.needsUpdate=true;});}const light=new THREE.PointLight(required?0xffd981:0x88bfff,1.7,4);light.position.set(0,.4,.3);g.add(light);const base=new THREE.Mesh(new THREE.BoxGeometry(.85,.75,.45),mats.dark);base.position.set(0,-.66,-.05);g.add(base);const tag=label((required?'关键照片':'可选照片')+' / E 拾取',position.x,position.y+.85,position.z,.68);pickups.push({photo,position,group:g,label:tag,taken:false,required});}
function updatePickupPrompt(now){
 let message='';if(!holding){
  const near=pickups.find(p=>!p.taken&&pos.distanceTo(p.position)<1.8);
  if(cameraPickup&&!cameraPickup.taken&&pos.distanceTo(cameraPickup.position)<1.7)message='E · 拾取相机 / 4 张胶卷';
  else if(near)message='E · 拾取「'+near.photo.name+'」';
  else if(carrying&&nearSocket())message='E · 将电池插入电源座';
  else if(batteryDock==='socket'&&nearSocket())message='已通电 · G 取回电池';
  else if(battery&&batteryDock==='ground'&&pos.distanceTo(batteryPos.clone().add(new V(0,1,0)))<2.2)message='E · 拿起电池';
  else if(nearCopier())message=levels[level].copierBattery&&batteryDock!=='copier'?(carrying?'E · 将电池插入复印机':'复印机已断电 · 去找前方电池'):photos.length?'E · 复印当前照片'+(batteryDock==='copier'?' / G 取回电池':''):'先拾取照片，再来复印';
 }
 $('interactPrompt').hidden=!message;$('interactPrompt').textContent=message;
 if(!reduceMotion)for(const p of pickups)if(!p.taken)p.group.position.y=p.position.y+Math.sin(now*.002)*.055;
}

function machinePart(parent,w,h,d,x,y,z,material){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material);mesh.position.set(x,y,z);parent.add(mesh);return mesh;}
function buildInteractions(){copier=new THREE.Group();copier.position.set(2.8,0,-2.5);decor.add(copier);machinePart(copier,1.25,.8,.9,0,.4,0,mats.stone);machinePart(copier,1.35,.15,1,0,.9,0,mats.gold);machinePart(copier,.9,.03,.65,-.1,1,0,mats.teal);copier.userData.lamp=machinePart(copier,.2,.06,.22,.5,1,.24,new THREE.MeshBasicMaterial({color:levels[level].copierBattery?0xd44a38:0x8fe7c1}));machinePart(copier,.75,.12,.35,0,.65,.5,mats.teal);copier.userData.paper=machinePart(copier,.62,.025,.42,0,.72,.45,mats.stone);copier.userData.until=0;label(levels[level].copierBattery?'复印机 / E 插电、复印 / G 拔电池':'复印机 / E 复制当前照片',2.8,1.55,-2.5,.75);box(2.8,.45,-2.5,1.25,.9,.9,'stone',true,false);
buildChapterProps();if(!battery)return;handBattery=battery.clone(true);handBattery.scale.setScalar(.65);handBattery.visible=false;decor.add(handBattery);socketPos=new V(levels[level].goal[0]-2,levels[level].goal[1],levels[level].goal[2]+3.5);socket=new THREE.Group();socket.position.copy(socketPos);decor.add(socket);machinePart(socket,.85,.72,.7,0,.36,0,mats.stone);machinePart(socket,.62,.1,.5,0,.77,0,mats.teal);socket.userData.lamp=machinePart(socket,.22,.16,.06,0,.46,.37,new THREE.MeshStandardMaterial({color:0xdf624b,emissive:0x6b1608}));label('电源插座 / E 插入电池',socketPos.x,socketPos.y+1.5,socketPos.z,.75);box(socketPos.x,socketPos.y+.35,socketPos.z,.85,.7,.7,'stone',true,false);const goal=new V(...levels[level].goal),points=[socketPos.clone().add(new V(0,.05,0)),new V(goal.x,socketPos.y+.05,socketPos.z),goal.clone().add(new V(0,.05,0))];const cable=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),24,.045,6,false),mats.gold);decor.add(cable);}
function nearCopier(){return copier&&pos.distanceTo(copier.position.clone().add(new V(0,1,0)))<2;}
function nearSocket(){return socketPos&&pos.distanceTo(socketPos.clone().add(new V(0,1,0)))<1.9;}
function updateBatteryVisual(){
 if(copier)copier.userData.lamp.material.color.set(!levels[level].copierBattery||batteryDock==='copier'?0x8fe7c1:0xd44a38);
 if(!battery)return;
 battery.visible=!carrying;
 battery.position.copy(batteryDock==='socket'?socketPos:batteryDock==='copier'?copier.position:batteryPos);
 if(batteryDock==='socket')battery.position.y+=.75;
 if(batteryDock==='copier')battery.position.add(new V(-.38,1.02,-.15));
 batteryLabel.visible=batteryDock==='ground';
 handBattery.visible=carrying&&mode==='play';
 handBattery.position.set(.56,-.65,-1).applyQuaternion(camera.quaternion).add(camera.position);
 handBattery.quaternion.copy(camera.quaternion);
 socket.userData.lamp.material.color.set(charged?0x81f3b0:0xdf624b);
 socket.userData.lamp.material.emissive.set(charged?0x235b32:0x6b1608);
}
function retrieveBattery(){
 if(mode!=='play'||develop||holding)return;
 if(batteryDock==='copier'&&nearCopier()||batteryDock==='socket'&&nearSocket()){
  batteryDock='hand';carrying=true;charged=false;portal.material.color.set(0x756a56);
  updateBatteryVisual();hud();notice('电池已取回，设备断电。把它带到下一个需要电的地方。');tone(340,.15);
 }else notice('靠近已插入电池的设备，放下照片后按 G 取回电池。');
}
function buildChapterProps(){
 if(level===2){
  box(1,.38,-2,.65,.76,.65,'wood',true,false);
  const g=new THREE.Group(),at=new V(1,1,-2);g.position.copy(at);decor.add(g);
  machinePart(g,.6,.42,.25,0,0,0,mats.dark);machinePart(g,.55,.1,.3,0,-.24,0,mats.gold);
  const lens=new THREE.Mesh(new THREE.CylinderGeometry(.14,.17,.18,24),mats.teal);lens.rotation.x=Math.PI/2;lens.position.z=.2;g.add(lens);
  machinePart(g,.18,.1,.12,.17,.25,0,glow);
  cameraPickup={group:g,position:at,taken:false,label:label('遗留的相机 / E 拾取',1,1.8,-2,.75)};
 }
 if(levels[level].copierBattery){
  box(5.5,1.65,-2.5,.2,3.3,4,'dark',true,false);label('停电的暗房 / 唯一的电源',3.6,2.9,-3.2,.9);
  for(let i=0;i<3;i++)machinePart(copier,.14,.18,.14,-.4+i*.19,1.05,-.32,mats.rust);
 }
 if(levels[level].temporal){
  for(const x of [-5.6,5.6]){box(x,.9,-8.3,1.8,1.8,.85,'rust');box(x,1.86,-8.3,2,.12,1,'cream');}
  label('1996 / 桥仍完整',-1.8,2.65,1.45,.7);
  label('如今 / 暴风雨后的庭院',0,6,-8.2,1.3);
  for(const [index,z] of [-11,-14].entries()){
   const x=index===0?-2.8:2.8,p=new THREE.Group();p.position.set(x,0,z);decor.add(p);
   machinePart(p,.7,1.5,.7,0,-.75,0,mats.dark);
   machinePart(p,.18,2.45,.18,0,1.2,0,mats.gold);
   machinePart(p,.8,.14,.8,0,2.25,0,mats.dark);
   const lamp=new THREE.Mesh(new THREE.SphereGeometry(.48,16,12),new THREE.MeshBasicMaterial({color:0x57e7ff}));lamp.position.y=2.85;p.add(lamp);
   const halo=new THREE.Mesh(new THREE.TorusGeometry(.73,.055,8,36),new THREE.MeshBasicMaterial({color:0x57e7ff}));halo.position.y=2.85;p.add(halo);
   const beam=new THREE.Mesh(new THREE.CylinderGeometry(.10,.24,3.4,8),new THREE.MeshBasicMaterial({color:0x57e7ff,transparent:true,opacity:.18,depthWrite:false}));beam.position.y=4.8;p.add(beam);
   const light=new THREE.PointLight(0x57e7ff,2.8,7);light.position.y=2.85;p.add(light);
   lamp.userData={index,halo,beam,light};memoryLamps.push(lamp);
   box(x,-1.7,z,1.1,3.4,1.2,'side');
   const ring=propMesh(new THREE.RingGeometry(.45,.52,32),new THREE.MeshBasicMaterial({color:0x57e7ff,side:THREE.DoubleSide}),0,.035,z);ring.rotation.x=-Math.PI/2;lamp.userData.ring=ring;
   label('0'+(index+1)+' / 记忆灯',x,3.95,z,.82,'#dcfcff');
  }

 }
}
function updateMemoryLights(){
 for(const lamp of memoryLamps){
  const color=restored?0xffd382:0x57e7ff;
  lamp.material.color.set(color);
  for(const key of ['halo','beam','ring'])lamp.userData[key].material.color.set(color);
  lamp.userData.light.color.set(color);lamp.userData.light.intensity=restored?4:2.8;
 }
}
function animateMemory(now){
 if(reduceMotion)return;
 for(const lamp of memoryLamps){const wave=.5+.5*Math.sin(now*.002+lamp.userData.index*1.5);lamp.userData.beam.material.opacity=restored?.24:.10+wave*.12;lamp.userData.halo.rotation.z=now*.00025;}
}

function updateMemory(photo,inserted){
 if(!levels[level].temporal)return;
 const hasBridge=[-11,-14].every(z=>records.some(r=>{if(!r.solid)return false;const c=S.column(r,0,z);return c&&c.ny>.55&&Math.abs(c.hi)<.45;}));
 const oldBridge=photo.era==='past'&&[-11,-14].every(z=>inserted.some(r=>{const c=S.column(r,0,z);return r.solid&&c&&c.ny>.55&&Math.abs(c.hi)<.45;}));
 restored=hasBridge&&(restored||oldBridge);charged=restored;updateMemoryLights();portal.material.color.set(charged?0xb5f2cf:0x756a56);
}

function copyPhoto(){if(levels[level].copierBattery&&batteryDock!=='copier'){notice('复印机没有电。先拾取电池，再靠近按 E 插入。');return;}if(!photos.length){notice('先拾取或拍摄一张照片，再放进复印机。');return;}if(photos.length>=5){notice('最多携带五张照片，先使用一张再复印。');return;}if(performance.now()<copier.userData.until)return;const original=photos[selected];photos.push({...original,name:original.name.replace(' · 复印','')+' · 复印',copy:true,starter:false});selected=photos.length-1;copier.userData.until=performance.now()+800;roll=0;distance=0;scale=1;rebuildPreview();inventory();hud();notice('复印完成：原件保留，新增一张一次性照片。');tone(620,.2);}

function addLandscape(n){if(n===0){const sea=propMesh(new THREE.PlaneGeometry(160,160),new THREE.MeshBasicMaterial({color:0x279bc2,transparent:true,opacity:.48,side:THREE.DoubleSide}),0,-10,-25);sea.rotation.x=-Math.PI/2;}if(n===1){for(let i=0;i<6;i++)propMesh(new THREE.ConeGeometry(8+i%2*3,12+i%3*4,6),mats.rust,-35+i*14,-8,-48);}if(n===2){for(let i=0;i<3;i++){const ring=propMesh(new THREE.TorusGeometry(4+i, .12,8,64),mats.teal,-16,5,-30);ring.rotation.set(i*.6,i*.8,.4);}}if(n===3){for(let i=0;i<65;i++){const a=i*2.399;propMesh(new THREE.SphereGeometry(.08+i%3*.035,5,4),glow,Math.sin(a)*52,8+i%13*2,-30-Math.cos(a)*25);}for(const [x,y,z] of levels[n].platforms){const light=new THREE.PointLight(0x8be9ee,3,16);light.position.set(x,y+3,z);decor.add(light);}}if(n===4){for(let i=0;i<3;i++)tree(-3.8+i*1.5,0,-4.7,.75);for(let i=0;i<4;i++)tree(-12,0,-12-i*4,1.5);}if(n===5){propMesh(new THREE.SphereGeometry(7,32,20),new THREE.MeshBasicMaterial({color:0xffe5b4}),4,11,-63);for(let i=0;i<4;i++){const o=propMesh(new THREE.TorusGeometry(4,.24,8,48),mats.rust,22+i*3,2+i*2,-38);o.rotation.y=.5;}}}
function planter(x,y,z,color='leaf'){
 box(x,y+.22,z,.95,.44,.9,'rust');
 const leaves=propMesh(new THREE.IcosahedronGeometry(.55,1),mats[color],x,y+.75,z);leaves.scale.y=.62;
}
function desk(x,z){
 box(x,.78,z,1.8,.12,.85,'wood');for(const dx of [-.7,.7])box(x+dx,.36,z,.1,.72,.65,'dark');
 for(let i=0;i<3;i++)box(x-.5+i*.4,.88,z,.3,.08,.48,['cream','rust','teal'][i],false);
}
function addWorldDetails(n){
 const half=levels[n].platforms[0][3]/2;
 for(const x of [-half+.8,half-.8]){planter(x,0,4.65);planter(x,0,-4.8);}
 if(n===0){desk(6.3,2.4);bench(6.4,0,4);label('海风茶歇',6.4,2.2,3.8,.7);}
 if(n===1){
  desk(-6.6,-.3);label('庭院档案 / 1996—2026',-6.6,2.1,-.3,.8);
  box(-8.4,1.35,-.6,.18,2.7,3,'wood');
  for(let i=0;i<3;i++){box(-8.05,.6+i*.68,-.6,.55,.08,2.8,'cream');for(let j=0;j<5;j++)box(-8.02,.85+i*.68,-1.65+j*.46,.34,.42,.27,['rust','teal','gold'][j%3]);}
  const basin=propMesh(new THREE.CylinderGeometry(1.25,1.4,.4,24),mats.cream,6.4,.2,.7);
  const water=propMesh(new THREE.CircleGeometry(1.13,32),new THREE.MeshStandardMaterial({color:0x35b7ce,transparent:true,opacity:.72,roughness:.2}),6.4,.41,.7);water.rotation.x=-Math.PI/2;
  box(6.4,.23,.7,2.5,.46,2.5,'cream',true,false);
  propMesh(new THREE.CylinderGeometry(.22,.35,.95,16),mats.gold,6.4,.89,.7);
  bench(6.3,0,3.7);label('雨后的喷泉',6.4,2.15,.7,.65);
  for(const x of [-6.3,6.3]){marker(x,0,-4.7);box(x,.35,-5.75,3.4,.7,.16,'cream');}
  label('观景台 / 远处青灯就是记忆点',6.4,1.7,-5.4,.7);
  for(const x of [-6.3,6.3]){tree(x,0,-22,.8);bench(x,0,-19.2);}
  arch(-5.7,0,-23);arch(5.7,0,-23);label('庭院的另一页',0,4.5,-24,.9);
  for(let i=0;i<5;i++){const x=12+i*4,z=-14-i*3;box(x,-3-i*.7,z,3,1,2.2,'side');arch(x,-2.5-i*.7,z);}
 }else if(n===2){
  for(let i=0;i<3;i++){box(6.4,.4,-2+i*1.8,1.2,.8,1.2,'side');const sculpture=propMesh(new THREE.TorusGeometry(.45,.13,8,24),mats[i%2?'rust':'gold'],6.4,1.45,-2+i*1.8);sculpture.rotation.y=i*.7;}
  label('光的展厅',6.4,2.5,1.6,.7);
 }else if(n===3){desk(-6.2,-.2);label('冲洗记录 / 停电前的最后一卷',-6.2,2,-.2,.75);for(let i=0;i<4;i++){box(-6.8+i*.4,1.75,4.7,.29,.37,.035,'cream',false);box(-6.8+i*.4,1.78,4.73,.23,.23,.025,'teal',false);}}
 else if(n===4){for(let i=0;i<3;i++)planter(-6.4,0,-2+i*1.8,i%2?'leaf2':'leaf');pergola(-5.6,0,-1.5);label('植物标本园',-6.2,2.6,-1,.75);}
 else if(n===5){const sundial=propMesh(new THREE.CylinderGeometry(1,1.2,.3,24),mats.cream,6.2,.35,1.7);box(6.2,.5,1.7,2,.4,2,'cream');propMesh(new THREE.ConeGeometry(.14,1.5,5),mats.gold,6.2,1.25,1.7);label('日光档案',6.2,2.5,1.7,.7);}
}
function jump(){if(mode==='play'&&!develop&&grounded){vy=5.8;grounded=false;}}

function record(faces,material='stone',solid=true,photoable=true){if(!faces.length)return null;const mesh=new THREE.Mesh(S.geometry(faces),mats[material]);mesh.castShadow=true;mesh.receiveShadow=true;const r={faces,material,solid,photoable,mesh,bounds:S.bounds(faces),planes:S.planes(faces)};records.push(r);group.add(mesh);return r;}
function box(x,y,z,w,h,d,material='stone',solid=true,photoable=true,rotation=0){let faces=S.box(x,y,z,w,h,d);if(rotation){const m=new M().makeTranslation(x,y,z).multiply(new M().makeRotationY(rotation)).multiply(new M().makeTranslation(-x,-y,-z));faces=S.transform(faces,m);}return record(faces,material,solid,photoable);}
function propMesh(geometry,material,x,y,z){const o=new THREE.Mesh(geometry,material);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;decor.add(o);return o;}
function label(text,x,y,z,size=2,color='#f7f0d6'){const c=document.createElement('canvas');c.width=768;c.height=144;const ct=c.getContext('2d');ct.fillStyle=color;ct.textAlign='center';ct.font='500 38px "Microsoft YaHei",sans-serif';ct.fillText(text,384,87);const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthWrite:false}));sprite.position.set(x,y,z);sprite.scale.set(size*3,size*.56,1);decor.add(sprite);return sprite;}
function tree(x,y,z,s=1){box(x,y+s*.65,z,.25*s,1.3*s,.25*s,'wood');for(let i=0;i<3;i++){const o=propMesh(new THREE.IcosahedronGeometry(s*(.72-i*.1),1),mats[i%2?'leaf2':'leaf'],x+Math.sin(i*3)*s*.24,y+s*(1.7+i*.28),z+Math.cos(i*3)*s*.15);o.scale.y=.83;}box(x,y+.2,z,1.5*s,.4,1.5*s,'rust');}
function bench(x,y,z,rot=0){box(x,y+.52,z,2.2,.14,.6,'wood',true,true,rot);for(const d of [-.8,.8])box(x+d*Math.cos(rot),y+.24,z-d*Math.sin(rot),.12,.48,.55,'dark');box(x,y+.95,z+.26,2.2,.58,.10,'wood',true,true,rot);}
function pergola(x,y,z){for(const a of [-2,2])for(const b of [-1.5,1.5])box(x+a,y+1.7,z+b,.18,3.4,.18,'wood');for(let i=0;i<7;i++)box(x-2.2+i*.72,y+3.48,z,.16,.17,3.8,'wood');box(x,y+3.32,z-1.5,4.5,.2,.17,'wood');box(x,y+3.32,z+1.5,4.5,.2,.17,'wood');}
function arch(x,y,z,rot=0){for(const a of [-1.7,1.7])box(x+a*Math.cos(rot),y+1.6,z-a*Math.sin(rot),.6,3.2,.75,'cream',true,true,rot);for(let i=0;i<9;i++){const a=(i+.5)*Math.PI/9;const o=propMesh(new THREE.BoxGeometry(.6,.65,.8),mats.cream,x+Math.cos(a)*1.7*Math.cos(rot),y+3.0+Math.sin(a)*1.7,z-Math.cos(a)*1.7*Math.sin(rot));o.rotation.set(0,rot,a-Math.PI/2);}}
function marker(x,y,z,rot=0){const o=propMesh(new THREE.RingGeometry(.55,.58,48),mats.gold,x,y+.025,z);o.rotation.x=-Math.PI/2;for(const a of [-.9,.9])box(x+a*Math.cos(rot),y+.02,z-a*Math.sin(rot),.09,.03,.6,'gold',false,false,rot);}
function artPanel(x,y,z,variant){box(x,y,z,2.5,2.0,.16,'wood');box(x,y,z+.1,2.25,1.75,.04,'white',false);box(x-.45,y-.1,z+.14,.75,1.25,.05,variant?'teal':'rust',false);box(x+.45,y+.1,z+.15,.65,.65,.05,'gold',false);box(x+.45,y-.55,z+.15,.75,.25,.05,'dark',false);}
function integrateDecor(){for(const o of [...decor.children]){if(!o.geometry||!['BoxGeometry','IcosahedronGeometry'].includes(o.geometry.type)||o.material.transparent)continue;const material=Object.keys(mats).find(k=>mats[k]===o.material);if(!material)continue;o.updateMatrix();const geo=o.geometry.index?o.geometry.toNonIndexed():o.geometry;const a=geo.attributes.position,faces=[];for(let i=0;i<a.count;i+=3)faces.push([0,1,2].map(j=>new V().fromBufferAttribute(a,i+j).applyMatrix4(o.matrix)));record(faces,material,true,true);decor.remove(o);if(geo!==o.geometry)geo.dispose();o.geometry.dispose();}}
function platform(x,y,z,w,d){box(x,y-.65,z,w,1.3,d,'stone');box(x,y-1.48,z,w-.4,.36,d-.4,'side');for(let i=1;i<w;i++)box(x-w/2+i,y+.007,z,.012,.014,d-.06,'side',false);for(let i=1;i<d;i++)box(x,y+.009,z-d/2+i,w-.06,.018,.012,'side',false);}
function makeSource(kind,x){const set=[];const add=(...args)=>{const r=box(...args);set.push(r);};add(x,-.35,1.5,4.4,.7,1,'cream');if(kind==='bridge'){add(x,-.35,-5,4.5,.7,12,'cream');for(const a of [-2.18,2.18]){add(x+a,.12,-5,.11,.24,12,'teal');for(let z=0;z>=-10;z-=2)add(x+a,.55,z,.1,1.1,.1,'wood');add(x+a,1.08,-5,.1,.12,12,'wood');}}else{for(let i=0;i<12;i++)add(x,(i+1)*.125-.25,.5-i,4.4,(i+1)*.25+.5,1,'cream');for(let i=0;i<12;i++){add(x-2.14,(i+1)*.25+.05,.5-i,.1,.1,1,'teal');add(x+2.14,(i+1)*.25+.05,.5-i,.1,.1,1,'teal');}}
if(kind!=='bridge')add(x,2.8,-12,4.4,.4,2,'cream');sourceSets[kind]={records:set,x};label(kind==='bridge'?'长桥 / STUDY 01':'阶梯 / STUDY 02',x,2.7,-5,1.8);return set;}
function cleanup(){const meshes=new Set(records.map(r=>r.mesh));for(const h of history)h.records.forEach(r=>meshes.add(r.mesh));meshes.forEach(m=>m.geometry.dispose());if(decor)decor.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material?.map){o.material.map.dispose();o.material.dispose();}});if(group)scene.remove(group);if(decor)scene.remove(decor);clearPreview();records=[];history=[];photos=[];sourceSets={};pickups=[];}
function clearPreview(){preview.traverse(o=>{if(o.geometry)o.geometry.dispose();});scene.remove(preview);preview=new THREE.Group();scene.add(preview);}
function buildLevel(n){cleanup();level=n;const d=levels[n];group=new THREE.Group();decor=new THREE.Group();scene.add(group,decor);applyTheme(n);sun.color.set(n===5?0xffcc98:0xffe8be);sun.intensity=n===1?2.2:3;hemi.intensity=n===1?1.7:2;charged=!d.battery&&!d.temporal;carrying=false;batteryDock='ground';restored=false;memoryLamps=[];cameraPickup=null;cameraOwned=n>2;film=n===3?0:4;battery=null;handBattery=null;socket=null;socketPos=null;batteryLabel=null;holding=false;selected=0;roll=0;distance=0;scale=1;develop=null;elapsed=0;
for(const p of d.platforms)platform(...p);const half=d.platforms[0][3]/2;box(0,.8,5.85,half*2-.2,1.6,.22,'cream');box(-half+.15,.8,1,.22,1.6,9.5,'cream');if(!d.east)box(half-.15,.8,1,.22,1.6,9.5,'cream');box(0,1.64,5.85,half*2,.12,.3,'rust');tree(-4.6,0,4.2,1);tree(4.7,0,4.4,.9);bench(-3.5,0,3.8);pergola(-5.2,0,2.5);arch(-4.5,0,-4.5,Math.PI/2);tree(-4.5,0,-3,1.1);box(-4.7,.2,-1.0,1.2,.4,1.4,'rust');
if(d.wall&&!d.temporal){box(0,2.8,-8.3,12,5.6,.85,'rust');box(0,5.72,-8.3,12.3,.25,1,'cream');for(let i=-5;i<=5;i+=2)box(i,2.8,-7.78,.12,5.6,.14,'cream');label('这不是尽头',0,4.7,-7.6,2);}
const gp=d.goal;const q=propMesh(new THREE.TorusGeometry(1.27,.13,12,64),mats.gold,gp[0],gp[1]+1.55,gp[2]);if(d.east||n===5)q.rotation.y=Math.PI/2;portal=propMesh(new THREE.CircleGeometry(1.16,64),new THREE.MeshBasicMaterial({color:charged?0xb5f2cf:0x756a56,side:THREE.DoubleSide,transparent:true,opacity:.78}),gp[0],gp[1]+1.55,gp[2]);portal.rotation.copy(q.rotation);box(gp[0],gp[1]+.1,gp[2],2.8,.2,2.8,'dark',false,false);label(charged?'传送 / 下一封来信':d.temporal?'修复旧桥 · 唤醒记忆':'需要一枚电池',gp[0],gp[1]+3.4,gp[2],1.4);tree(gp[0]+3,gp[1],gp[2]+1.3,1.2);bench(gp[0]-2.5,gp[1],gp[2]+1);
for(let i=1;i<d.platforms.length;i++){const [x,y,z,w,dp]=d.platforms[i];if(w>8)pergola(x-2.5,y,z+dp/2-2);tree(x-w/2+.9,y,z-dp/2+1,.8);}
if(n===4){for(let i=0;i<4;i++)tree(23,3,-3+i*2,1+i*.12);pergola(21,3,-2);}
if(n===5){arch(0,0,-21);pergola(22,3,-22);}
if(n===0){for(let i=0;i<4;i++)box(-3.8+i*.32,.72,3.8,.24,.14,.42,['rust','teal','gold','cream'][i]);label('风会记得你来过',-4,2.5,4.8,.8);}
if(n===1){artPanel(3,1.9,5.68,0);}
if(n===2){artPanel(-2.5,2.1,5.68,1);artPanel(1,2.1,5.68,0);box(3.9,.85,1.6,1,1.7,1,'side');propMesh(new THREE.IcosahedronGeometry(.62,0),mats.gold,3.9,2.25,1.6);label('换一种方式观看',0,4,5.4,1.2);}
if(n===3){for(let i=0;i<4;i++){arch(-8,-2,-12-i*5);box(-8,-2.8,-12-i*5,5,1.2,2,'side');}bench(2,0,-18);label('在这里，把风景再用一次',0,3,-20.8,1.2);}
if(n===4){for(let i=0;i<3;i++){tree(-4.6,0,-2+i*1.8,.72);box(4,0.25,-4+i*1.1,1.3,.5,.85,'rust');}label('把光带回来',20,6,-3,1.3);}
if(n===5){for(let i=0;i<3;i++){arch(-8,2+i*2,-17-i*5);box(-8,1.1+i*2,-17-i*5,5,.7,2,'side');}label('所有来信，终有回响',23,7,-22,1.6);}
marker(0,0,-4);if(d.east)marker(4,0,0,-Math.PI/2);if(n===3)marker(0,0,-21);if(n===5)marker(3,0,-19,-Math.PI/2);
makeSource('bridge',-24);makeSource('stairs',-38);makeExtraSource(['archway','stepping','ramp'][n%3],-52);addLandscape(n);addWorldDetails(n);
for(let i=0;i<20;i++){const a=i*2.399,r=32+i%4*9,x=Math.sin(a)*r,z=Math.cos(a)*r-17;const o=propMesh(new THREE.BoxGeometry(3+i%4,7+i%6*2,3+i%3),mats.side,x,-12-i%3*3,z);if(i%3===0){propMesh(new THREE.BoxGeometry(7,.5,7),mats.cream,x,-5-i%3*3,z);const cloud=propMesh(new THREE.IcosahedronGeometry(5,1),new THREE.MeshBasicMaterial({color:0xf2eddb,transparent:true,opacity:.19,depthWrite:false}),x,-8,z);cloud.scale.set(2,.18,1);}}
for(let i=0;i<12;i++){const p=propMesh(new THREE.SphereGeometry(.035,5,4),glow,Math.sin(i*3)*8,2+i%5,Math.cos(i*2)*8-5);p.userData.mote=i;}
if(d.battery){batteryPos=new V(...d.battery);battery=new THREE.Group();decor.add(battery);battery.position.copy(batteryPos);const body=new THREE.Mesh(new THREE.BoxGeometry(.48,.65,.38),mats.gold);body.position.y=.48;battery.add(body);const band=new THREE.Mesh(new THREE.BoxGeometry(.49,.18,.39),glow);band.position.y=.48;battery.add(band);batteryLabel=label('电池 / E 拿起',batteryPos.x,batteryPos.y+1.35,batteryPos.z,1.1);}
integrateDecor();buildInteractions();scene.updateMatrixWorld(true);for(const kind of d.starter){const k=kind==='turned'?'stairs':kind;const source=sourceSets[k];const shot=new THREE.PerspectiveCamera(48,1.4,.85,19);shot.rotation.order='YXZ';shot.position.set(source.x,1.68,3);shot.rotation.x=-.32;shot.rotation.z=kind==='turned'?Math.PI/2:0;shot.updateMatrixWorld(true);const photo=makePhoto(shot,source.records,kind==='bridge'?'长桥的来信':kind==='turned'?'侧躺的阶梯':'向上的阶梯',true,d.temporal?'sepia':'color');if(d.temporal){photo.name='1996 · 完好的庭院长桥';photo.era='past';}const middle=n===5&&kind==='stairs';spawnPickup(photo,middle?new V(1.5,1.02,-18.6):new V(-1.8,1.02,1.45),true);}
const optionalKind=['archway','stepping','ramp'][n%3],optional=sourceSets[optionalKind];const extraCam=new THREE.PerspectiveCamera(48,1.4,.85,19);extraCam.rotation.order='YXZ';extraCam.position.set(optional.x,1.68,3);extraCam.rotation.x=-.25;const style=n%2?'sepia':'blue';const extra=makePhoto(extraCam,optional.records,{archway:'蓝晒 · 拱门',stepping:'旧画 · 浮石',ramp:'蓝晒 · 斜坡'}[optionalKind],true,style);if(style==='sepia')extra.name=extra.name.replace('蓝晒','旧画');else extra.name=extra.name.replace('旧画','蓝晒');spawnPickup(extra,new V(2.65,1.02,2.6),false);
pos.set(0,1.68,3.6);safe.copy(pos);yaw=0;pitch=0;vy=0;grounded=true;$('levelNo').textContent=`0${n+1} — 06`;$('levelName').textContent=d.name;rebuildPreview();inventory();hud();resize();}
function imageFromCamera(cam,style='color'){const oldTarget=renderer.getRenderTarget(),oldSize=renderer.getSize(new THREE.Vector2());const target=new THREE.WebGLRenderTarget(560,400);target.texture.colorSpace=THREE.SRGBColorSpace;const was=preview.visible,held=handBattery?.visible;preview.visible=false;if(handBattery)handBattery.visible=false;renderer.setRenderTarget(target);renderer.render(scene,cam);const pixels=new Uint8Array(560*400*4);renderer.readRenderTargetPixels(target,0,0,560,400,pixels);renderer.setRenderTarget(oldTarget);preview.visible=was;if(handBattery)handBattery.visible=held;const c=document.createElement('canvas');c.width=560;c.height=400;const ct=c.getContext('2d'),img=ct.createImageData(560,400);for(let y=0;y<400;y++)img.data.set(pixels.subarray((399-y)*560*4,(400-y)*560*4),y*560*4);if(style!=='color')for(let i=0;i<img.data.length;i+=4){const l=(img.data[i]*.2126+img.data[i+1]*.7152+img.data[i+2]*.0722)/255;const rgb=style==='blue'?[18+190*l,45+195*l,105+140*l]:[60+182*l,38+170*l,22+140*l];img.data[i]=rgb[0];img.data[i+1]=rgb[1];img.data[i+2]=rgb[2];}ct.putImageData(img,0,0);target.dispose();return c.toDataURL('image/jpeg',.88);}
function makePhoto(cam,candidates,name,starter=false,style='color'){cam.updateMatrixWorld(true);const cut=S.frustum(cam.matrixWorld,48,1.4,.85,19),inv=cam.matrixWorld.clone().invert(),items=[];for(const r of candidates){if(!r.photoable)continue;const faces=S.intersect(r.faces,cut);if(faces.length)items.push({faces:S.transform(faces,inv),material:style==='color'?r.material:style==='blue'?(['cream','stone','white'].includes(r.material)?'photoWhite':'photoBlue'):(['cream','stone','white'].includes(r.material)?'photoOchre':'photoUmber'),solid:r.solid});}const far=Math.min(19,Math.max(1.2,...items.flatMap(i=>i.faces.flat().map(v=>-v.z)))+.015);return {items,image:imageFromCamera(cam,style),name,starter,pitch:cam.rotation.x,far,style};}
function capture(){if(mode!=='play'||develop)return;if(!cameraOwned){notice(level<2?'先学会使用来信照片。第三关会找到相机。':'先到前方工作台，按 E 拾取相机。');return;}if(film<=0){notice(levels[level].copierBattery?'暗房没有胶卷：用电池启动复印机，复制已有照片。':'胶卷已用完。使用已有照片或复印机，Z 可回到上次显影前。');return;}syncCamera();const shot=new THREE.PerspectiveCamera(48,1.4,.85,19);shot.rotation.order='YXZ';shot.position.copy(camera.position);shot.quaternion.copy(camera.quaternion);const p=makePhoto(shot,records,`现场 / ${String(photos.length+1).padStart(2,'0')}`);if(!p.items.length){notice('这一帧只有天空。把建筑或地面纳入取景框。');return;}if(p.items.length>240){notice('画面过于复杂，请靠近并缩小取景范围。');return;}if(photos.length>=5){const index=photos.findIndex(p=>!p.starter);photos.splice(index<0?photos.length-1:index,1);}film--;photos.push(p);selected=photos.length-1;holding=false;roll=0;distance=0;scale=1;rebuildPreview();inventory();hud();flash('flash');tone(980,.055);setTimeout(()=>tone(440,.12),75);notice(`拍下了你眼前的空间。按 C 举起，寻找新的放置位置。`);}
function rebuildPreview(){clearPreview();const photo=photos[selected];if(!photo)return;for(const item of photo.items){const o=new THREE.Mesh(S.geometry(item.faces),ghostMat);preview.add(o);}preview.matrixAutoUpdate=false;preview.visible=holding;}
function pose(){syncCamera();const forward=new V(0,0,-1).applyQuaternion(camera.quaternion);return new M().compose(pos.clone().addScaledVector(forward,distance),camera.quaternion,new V(1,1,1)).multiply(new M().makeRotationZ(roll*Math.PI/180)).multiply(new M().makeScale(scale,scale,scale));}
function toggle(){if(mode!=='play'||develop)return;if(!photos.length){notice('先走到附近发光的相片架旁，按 E 拾取。取得相机后才可以 F 拍摄。');return;}holding=!holding;if(holding){pitch=photos[selected].pitch;rebuildPreview();}hud();}
function rotate(dir){if(!holding)return;roll=(roll+dir*90+360)%360;hud();}
function cycle(){if(!photos.length)return;selected=(selected+1)%photos.length;roll=0;distance=0;scale=1;rebuildPreview();inventory();hud();}
function deploy(){if(mode!=='play'||develop)return;if(!holding){interact();return;}const photo=photos[selected];if(!photo)return;if(history.length>=12){notice('本关已显影 12 次，可按 Z 回溯后重新构图。');return;}const matrix=pose(),planes=S.frustum(matrix,48,1.4,.85,photo.far);const next=[],added=[];let removed=0;
for(const r of records){if(!r.photoable){next.push(r);continue;}const inside=S.intersect(r.faces,planes);if(!inside.length){next.push(r);continue;}removed++;for(const f of S.subtract(r.faces,planes))next.push({faces:f,material:r.material,solid:r.solid,photoable:r.photoable});}
for(const item of photo.items){const p={faces:S.transform(item.faces,matrix),material:item.material,solid:item.solid,photoable:true};next.push(p);added.push(p);}if(next.length>1600){notice('空间太复杂了。请回溯一次，或选择更小的构图。');return;}
history.push({cameraOwned,film,batteryDock,restored,cameraTaken:cameraPickup?.taken,photos:photos.slice(),taken:pickups.map(p=>p.taken),records:records.slice(),position:pos.clone(),yaw,pitch,selected,roll,distance,scale,carrying,charged,batteryPos:batteryPos?.clone()});const before=records;records=[];for(const r of before)group.remove(r.mesh);const inserted=[];for(const r of next){if(r.mesh){records.push(r);group.add(r.mesh);}else{const created=record(r.faces,r.material,r.solid,r.photoable);if(added.includes(r))inserted.push(created);}}
updateMemory(photo,inserted);photos.splice(selected,1);selected=Math.max(0,Math.min(selected,photos.length-1));holding=false;rebuildPreview();inventory();preview.visible=false;const inv=matrix.clone().invert();const animations=inserted.map(r=>{const attr=r.mesh.geometry.attributes.position,full=attr.array.slice(),flat=full.slice();for(let i=0;i<full.length;i+=3){const v=new V(full[i],full[i+1],full[i+2]).applyMatrix4(inv);v.multiplyScalar(3/Math.max(.3,-v.z)).applyMatrix4(matrix);flat[i]=v.x;flat[i+1]=v.y;flat[i+2]=v.z;}return {r,full,flat};});develop={time:0,animations};flash('developLine');tone(300,.4);setTimeout(()=>tone(520,.5),120);hud();notice(levels[level].temporal?(restored?'旧桥回到了庭院，两盏记忆灯亮起。出口已开启。':'旧照片已展开，但桥还未连接两盏记忆灯。Z 回溯后重新对齐。'):removed?'照片展开了，画框内的原有空间也被改写。':'照片已经成为新的、可以行走的空间。');}
function undo(){if(mode!=='play'||develop)return;if(!history.length){notice('还没有显影记录。');return;}const h=history.pop();records.forEach(r=>group.remove(r.mesh));records=h.records;records.forEach(r=>group.add(r.mesh));pos.copy(h.position);safe.copy(pos);yaw=h.yaw;pitch=h.pitch;vy=0;photos=h.photos;pickups.forEach((p,i)=>{p.taken=h.taken[i];p.group.visible=p.label.visible=!p.taken;});selected=Math.max(0,Math.min(h.selected,photos.length-1));roll=h.roll;distance=h.distance;scale=h.scale;cameraOwned=h.cameraOwned;film=h.film;batteryDock=h.batteryDock;restored=h.restored;if(cameraPickup){cameraPickup.taken=h.cameraTaken;cameraPickup.group.visible=cameraPickup.label.visible=!cameraPickup.taken;}updateMemoryLights();carrying=h.carrying;charged=h.charged;batteryPos=h.batteryPos;updateBatteryVisual();portal.material.color.set(charged?0xb5f2cf:0x756a56);holding=false;rebuildPreview();inventory();hud();notice('空间已回到上一次显影之前，被切掉的建筑也已恢复。');tone(210,.25);}
function interact(){const d=levels[level];if(cameraPickup&&!cameraPickup.taken&&pos.distanceTo(cameraPickup.position)<1.7){cameraPickup.taken=true;cameraPickup.group.visible=cameraPickup.label.visible=false;cameraOwned=true;film=4;hud();notice('找到相机，装有 4 张胶卷。F 拍摄眼前的建筑，照片仍是一次性使用。');tone(820,.2);return;}const found=pickups.find(p=>!p.taken&&pos.distanceTo(p.position)<1.8);if(found){if(photos.length>=5){const replace=photos.findIndex(p=>!p.starter);if(replace<0){notice('照片收藏已满，请先完成当前关卡。');return;}photos.splice(replace,1);}found.taken=true;found.group.visible=false;found.label.visible=false;photos.push(found.photo);selected=photos.length-1;roll=0;distance=0;scale=1;rebuildPreview();inventory();hud();notice('已拾取「'+found.photo.name+'」。C 举起照片，E 将它放进世界。');tone(740,.15);return;}if(battery&&batteryDock==='ground'&&pos.distanceTo(batteryPos.clone().add(new V(0,1,0)))<2.2){batteryDock='hand';carrying=true;battery.visible=false;hud();updateBatteryVisual();notice('拿起电池。找到电缆连接的独立电源插座，按 E 插入。');tone(770,.12);return;}if(carrying&&nearSocket()){batteryDock='socket';charged=true;carrying=false;portal.material.color.set(0xb5f2cf);hud();updateBatteryVisual();notice('电池已插入电源座，传送门已供电。走进光里。');return;}if(nearCopier()){if(d.copierBattery&&carrying){batteryDock='copier';carrying=false;updateBatteryVisual();hud();notice('复印机已通电。E 复印当前照片；完成后 G 取回电池。');return;}copyPhoto();return;}notice(holding?'E 放置照片':'C 举起照片 · F 拍摄当前画面');}
function inventory(){$('inventory').replaceChildren();photos.forEach((p,i)=>{const b=document.createElement('button');b.className='thumb'+(i===selected?' active':'');b.setAttribute('aria-label',`选择照片 ${i+1}：${p.name}`);const img=document.createElement('img');img.src=p.image;img.alt=p.name;const text=document.createElement('span');text.textContent=`0${i+1} / ${p.copy?'复印':p.starter?'来信':'现场'}`;b.append(img,text);b.onclick=()=>{selected=i;roll=0;distance=0;scale=1;rebuildPreview();inventory();hud();};$('inventory').appendChild(b);});}
function hud(){document.documentElement.classList.toggle('projecting',holding);const d=levels[level];$('objective').textContent=d.temporal||photos.length||history.length?d.title:'先找到附近的照片。';$('hint').textContent=d.temporal||photos.length||history.length?d.hint:'左前方的发光相片架上有一张照片。走近后按 E 拾取；空格可以跳跃。';$('photoBox').hidden=!holding;$('photoSettings').hidden=!holding;$('cameraBody').hidden=holding||carrying||!cameraOwned;$('touchF').disabled=!cameraOwned||film<=0;$('cameraStatus').textContent=cameraOwned?(film?'相机 · 胶卷 '+film+' / 4':'相机 · 无胶卷'):level<2?'相机尚未获得 · 第三关解锁':'相机在前方工作台 · E 拾取';$('touchG').hidden=!levels[level].battery;$('batteryStatus').hidden=!carrying;$('memoryStatus').hidden=!d.temporal;$('memoryStatus').textContent=restored?'01 ●   02 ●  记忆已修复 · 出口开启':'01 ◇   02 ◇  断桥两侧的青色灯柱 · 等待旧桥';document.querySelector('.reticle').classList.toggle('aiming',!holding);preview.visible=holding;const p=photos[selected];if(p){$('photoImg').src=p.image;$('photoName').textContent=p.name;}$('photoAngle').textContent=`${roll}°`;$('photoBox').style.transform=`translate(-50%,-50%) rotate(${-roll}deg)`;$('transformReadout').textContent=`旋转 ${roll}° / 距离 ${distance.toFixed(1)} m / 比例 ${scale.toFixed(2)}`;$('saveStatus').textContent=`${photos.length} 张照片 · ${history.length} 次显影`;$('reticleLabel').textContent=holding?'ALIGN / PLACE':cameraOwned&&film?'F / 捕捉眼前的空间':'E / 探索与拾取';}
function notice(s){$('notice').textContent=s;$('notice').classList.add('show');noticeEnd=performance.now()+4800;}
function flash(id){$(id).classList.remove('fire');void $(id).offsetWidth;$(id).classList.add('fire');}
function syncCamera(){camera.position.copy(pos);camera.rotation.set(pitch,yaw,0);camera.updateMatrixWorld(true);}
function canMove(x,z){const feet=pos.y-1.68;for(const r of records){if(!r.solid)continue;for(const [dx,dz] of [[0,0],[.2,0],[-.2,0],[0,.2],[0,-.2]]){const c=S.column(r,x+dx,z+dz);if(c&&c.hi>feet+.34&&c.lo<pos.y-.2)return false;}}return true;}
function walk(dt){const speed=(keys.has('ShiftLeft')?5.8:3.7)*dt;let x=Number(keys.has('KeyD'))-Number(keys.has('KeyA')),z=Number(keys.has('KeyW'))-Number(keys.has('KeyS'));const l=Math.hypot(x,z)||1;x/=l;z/=l;const dx=(x*Math.cos(yaw)-z*Math.sin(yaw))*speed,dz=(-x*Math.sin(yaw)-z*Math.cos(yaw))*speed;if(canMove(pos.x+dx,pos.z))pos.x+=dx;if(canMove(pos.x,pos.z+dz))pos.z+=dz;const feet=pos.y-1.68;let floor=-Infinity;for(const r of records){if(!r.solid)continue;const c=S.column(r,pos.x,pos.z);if(c&&c.ny>.55&&c.hi<=feet+.34)floor=Math.max(floor,c.hi);}if(vy<=0&&feet>=floor-.34&&feet-floor<.4){pos.y=floor+1.68;vy=0;grounded=true;}else{vy-=14*dt;pos.y+=vy*dt;grounded=false;if(pos.y-1.68<floor&&feet>=floor){pos.y=floor+1.68;vy=0;grounded=true;}}
for(const [a,h,b,w,d] of levels[level].platforms)if(grounded&&Math.abs(pos.x-a)<w/2-1&&Math.abs(pos.z-b)<d/2-1&&Math.abs(pos.y-1.68-h)<.1)safe.copy(pos);
if(pos.y<-12){pos.copy(safe);vy=0;notice('回到最近的露台。也可以按 Z 回溯显影。');}if(keys.has('ArrowLeft'))yaw+=dt*1.3;if(keys.has('ArrowRight'))yaw-=dt*1.3;if(keys.has('ArrowUp'))pitch=Math.min(1.25,pitch+dt);if(keys.has('ArrowDown'))pitch=Math.max(-1.25,pitch-dt);const d=levels[level];if(charged&&Math.hypot(pos.x-d.goal[0],pos.z-d.goal[2])<1.0&&Math.abs(pos.y-1.68-d.goal[1])<.7)finish();syncCamera();}
function setMode(m){mode=m;document.documentElement.classList.toggle('playing',m==='play');keys.clear();drag=false;$('intro').hidden=m!=='intro';$('hud').hidden=m==='intro';$('pause').hidden=m!=='pause';$('complete').hidden=m!=='complete';$('pauseBtn').hidden=m==='intro';if(m!=='play'&&document.pointerLockElement)document.exitPointerLock();}
function save(){try{localStorage.setItem('afterimage-v2',JSON.stringify({unlocked:maxUnlocked,level}));}catch{}}
function finish(){total+=elapsed;maxUnlocked=Math.min(5,Math.max(maxUnlocked,level+1));save();setMode('complete');$('completeTag').textContent=`来信 0${level+1} / 已抵达`;$('completeTitle').textContent=level===5?'你把六个不可能，连成了一个世界。':'光，已经抵达。';$('completeText').textContent=level===5?`六个章节已完成。用过的照片，也可以成为新的取景。`:`${levels[level].name} · ${history.length} 次显影 · ${Math.floor(elapsed/60)} 分 ${Math.floor(elapsed%60)} 秒`;$('next').textContent=level===5?'回到风的庭院 ↺':'下一封明信片 →';tone(650,.2);setTimeout(()=>tone(980,.35),150);chapters();}
function chapters(){$('chapterSelect').replaceChildren();levels.forEach((d,i)=>{const b=document.createElement('button');b.textContent=String(i+1).padStart(2,'0');b.title=d.name;b.disabled=i>maxUnlocked;b.onclick=()=>{buildLevel(i);setMode('play');};$('chapterSelect').appendChild(b);});}
let audio;function tone(f,d){try{audio ||=new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(.03,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d);}catch{}}
function lock(){try{const p=renderer.domElement.requestPointerLock?.();if(p?.catch)p.catch(()=>{});}catch{}}
function start(n){total=0;buildLevel(n);setMode('play');save();lock();notice('直接移动鼠标环顾。走到左前方的照片旁按 E 拾取，空格跳跃。');}
const actions={KeyG:retrieveBattery,KeyF:capture,KeyC:toggle,KeyE:deploy,KeyQ:()=>rotate(-1),KeyR:()=>rotate(1),KeyX:cycle,KeyZ:undo,KeyH:()=>notice(levels[level].help),KeyT:()=>{buildLevel(level);notice('本关已重新开始。');},Minus:()=>{scale=Math.max(.7,scale-.1);hud();},Equal:()=>{scale=Math.min(1.7,scale+.1);hud();}};
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if(mode==='play')setMode('pause');else if(mode==='pause')setMode('play');return;}if(mode!=='play'||develop)return;keys.add(e.code);if(!e.repeat&&actions[e.code])actions[e.code]();if(e.code==='Space'&&!e.repeat)jump();});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();drag=false;if(mode==='play')setMode('pause');});
const canvas=renderer.domElement;canvas.addEventListener('pointerdown',e=>{if(mode!=='play')return;drag=true;px=e.clientX;py=e.clientY;canvas.setPointerCapture(e.pointerId);if(e.pointerType==='mouse'&&!document.pointerLockElement)lock();});canvas.addEventListener('pointermove',e=>{if(mode!=='play')return;if(document.pointerLockElement===canvas){yaw-=e.movementX*.0025;pitch-=e.movementY*.0025;}else if(e.pointerType!=='touch'){yaw-=(Number.isFinite(e.movementX)?e.movementX:e.clientX-px)*.0025;pitch-=(Number.isFinite(e.movementY)?e.movementY:e.clientY-py)*.0025;}else if(drag){yaw-=(e.clientX-px)*.004;pitch-=(e.clientY-py)*.004;}pitch=Math.max(-1.25,Math.min(1.25,pitch));px=e.clientX;py=e.clientY;});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('pointercancel',()=>drag=false);canvas.addEventListener('contextmenu',e=>e.preventDefault());addEventListener('wheel',e=>{if(mode==='play'&&holding){e.preventDefault();distance=Math.max(-1,Math.min(7,distance+Math.sign(e.deltaY)*.3));hud();}},{passive:false});
$('start').onclick=()=>start(0);$('continue').onclick=()=>start(maxUnlocked);$('pauseBtn').onclick=()=>setMode(mode==='pause'?'play':'pause');$('resume').onclick=()=>{setMode('play');lock();};$('next').onclick=()=>{buildLevel((level+1)%6);setMode('play');lock();save();};$('placeButton').onclick=deploy;$('helpBtn').onclick=()=>notice(levels[level].help);for(const [id,fn] of Object.entries({touchG:retrieveBattery,touchF:capture,touchC:toggle,touchR:()=>rotate(1),touchE:deploy,touchX:cycle,touchZ:undo,touchJump:jump}))$(id).onclick=fn;document.querySelectorAll('[data-move]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();keys.add(b.dataset.move);b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.move);});
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();const h=Math.min(innerHeight*Math.tan(24*Math.PI/180)/Math.tan(32.5*Math.PI/180),innerWidth*.72/1.4),w=h*1.4;document.documentElement.style.setProperty('--frameW',`${w}px`);document.documentElement.style.setProperty('--frameH',`${h}px`);}addEventListener('resize',resize);
try{const saved=JSON.parse(localStorage.getItem('afterimage-v2'));if(saved)maxUnlocked=Math.min(5,Math.max(0,Number(saved.unlocked)||0));}catch{}$('continue').hidden=maxUnlocked===0;buildLevel(0);chapters();setMode('intro');let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.04);last=now;if(mode==='play'){elapsed+=dt;if(develop){develop.time+=dt;const t=reduceMotion?1:Math.min(1,develop.time/.65),e=1-Math.pow(1-t,3);for(const a of develop.animations){const attr=a.r.mesh.geometry.attributes.position;for(let i=0;i<a.full.length;i++)attr.array[i]=a.flat[i]+(a.full[i]-a.flat[i])*e;attr.needsUpdate=true;}if(t===1){for(const a of develop.animations){a.r.mesh.geometry.computeVertexNormals();a.r.mesh.geometry.computeBoundingSphere();}develop=null;}}else walk(dt);updatePickupPrompt(now);animateMemory(now);if(holding){preview.matrix.copy(pose());preview.visible=true;}}else if(mode==='intro'){camera.position.set(15,9,15);camera.lookAt(-2,.3,-6);}updateBatteryVisual();if(copier)copier.userData.paper.position.z=.45+Math.max(0,(copier.userData.until-now)/800)*.25;if(portal&&!reduceMotion)portal.material.opacity=.7+Math.sin(now*.0018)*.08;if(!reduceMotion)for(const o of decor.children)if(o.userData.mote!==undefined)o.position.y+=Math.sin(now*.0008+o.userData.mote)*dt*.05;if(now>noticeEnd)$('notice').classList.remove('show');renderer.render(scene,camera);}requestAnimationFrame(frame);
window.afterimage={getState:()=>({version:6,memoryLamps:memoryLamps.map(l=>({position:l.getWorldPosition(new V()).toArray(),color:l.material.color.getHex()})),mapPlatforms:levels[level].platforms,cameraOwned,film,batteryDock,restored,cameraPickup:cameraPickup?{taken:cameraPickup.taken,position:cameraPickup.position.toArray()}:null,handBatteryVisible:!!handBattery?.visible,socketPosition:socketPos?.toArray(),copierPosition:copier?.position.toArray(),level,mode,holding,roll,distance,scale,photos:photos.map(p=>({name:p.name,parts:p.items.length})),selected,history:history.length,solids:records.length,position:pos.toArray(),yaw,pitch,carrying,charged,developing:!!develop,grounded,vy,pickups:pickups.map(p=>({name:p.photo.name,taken:p.taken,position:p.position.toArray(),required:p.required})),theme:themes[level].name}),snapshot:()=>renderer.domElement.toDataURL('image/png')};
})();
